steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - gcr.io/ldk-clean/voice-bridge-service
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/ldk-clean/voice-bridge-service

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - voice-bridge-service
      - --image=gcr.io/ldk-clean/voice-bridge-service:latest
      - --region=europe-west1
      - --project=ldk-clean
      - --update-secrets=TELNYX_API_KEY=TELNYX_API_KEY:latest
      - --quiet

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - voice-bridge-service
      - --to-latest
      - --region=europe-west1
      - --project=ldk-clean

images:
  - gcr.io/ldk-clean/voice-bridge-service

options:
  logging: CLOUD_LOGGING_ONLY
