steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - gcr.io/ldk-clean/voice-bridge-service
      - .

images:
  - gcr.io/ldk-clean/voice-bridge-service
