steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile.control-plane
      - -t
      - gcr.io/ldk-clean/control-plane-service
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/ldk-clean/control-plane-service

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - control-plane-service
      - --image=gcr.io/ldk-clean/control-plane-service:latest
      - --region=europe-west1
      - --project=ldk-clean
      - --quiet

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - control-plane-service
      - --to-latest
      - --region=europe-west1
      - --project=ldk-clean

images:
  - gcr.io/ldk-clean/control-plane-service

options:
  logging: CLOUD_LOGGING_ONLY
