steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile.telephony
      - -t
      - gcr.io/ldk-clean/telephony-service
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/ldk-clean/telephony-service

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - telephony-service
      - --image=gcr.io/ldk-clean/telephony-service:latest
      - --region=europe-west1
      - --project=ldk-clean
      - --update-secrets=TELNYX_API_KEY=TELNYX_API_KEY:latest,TELNYX_PUBLIC_KEY=TELNYX_PUBLIC_KEY:latest
      - --allow-unauthenticated
      - --no-cpu-throttling
      - --min-instances=0
      - --max-instances=20
      - --quiet

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - telephony-service
      - --to-latest
      - --region=europe-west1
      - --project=ldk-clean

images:
  - gcr.io/ldk-clean/telephony-service

options:
  logging: CLOUD_LOGGING_ONLY
