FROM node:20-alpine

WORKDIR /app/apps/post-processor

COPY apps/post-processor/package*.json ./
RUN npm install --omit=dev

COPY apps/post-processor/index.js ./
COPY apps/post-processor/lib ./lib

EXPOSE 8080
CMD ["node", "index.js"]
